updated to trigger work flow

diff --git a/.github/workflows/Test.yml b/.github/workflows/Test.yml
--- a/.github/workflows/Test.yml
+++ b/.github/workflows/Test.yml
@@ -2,11 +2,12 @@
 on:
   workflow_run:
     workflows: ["Train"]
-    types:
+    types: 
       - completed
 
 jobs:
-  pull-and-run:
+  on-success:
+    pull-and-run: 
     if: ${{ github.event.workflow_run.conclusion == 'success' }}
 
     runs-on: ubuntu-latest
@@ -23,3 +24,9 @@ jobs:
           else
             echo "Score is not more than 0.35, job is failed."
             exit 1
+   on-failure:
+      if: ${{ github.event.workflow_run.conclusion == 'failure' }}
+
+      runs-on: ubuntu-latest
+         echo "Train workflow is failed"
+         exit 1
